import { createServiceClient } from '@/lib/supabase/service'

// ─── Error Types ──────────────────────────────────────────────────────────────

export type CreateQrTokenErrorCode =
  | 'INCIDENT_NOT_FOUND'
  | 'INCIDENT_CLOSED'
  | 'DB_ERROR'

export class CreateQrTokenError extends Error {
  constructor(
    public readonly code: CreateQrTokenErrorCode,
    message: string,
  ) {
    super(message)
    this.name = 'CreateQrTokenError'
  }
}

// ─── Result Type ──────────────────────────────────────────────────────────────

export interface CreateQrTokenResult {
  id: string
  token: string
}

// ─── Business Logic ───────────────────────────────────────────────────────────

export async function createQrToken(
  organizationId: string,
  incidentId: string,
  memberId: string,
): Promise<CreateQrTokenResult> {
  const supabase = createServiceClient()

  // Verify the incident exists, belongs to this org, and is not closed
  const { data: incident, error: incidentError } = await supabase
    .from('incidents')
    .select('id, status')
    .eq('id', incidentId)
    .eq('organization_id', organizationId)
    .is('deleted_at', null)
    .maybeSingle()

  if (incidentError || !incident) {
    throw new CreateQrTokenError('INCIDENT_NOT_FOUND', 'Incident not found')
  }

  if (incident.status === 'closed') {
    throw new CreateQrTokenError(
      'INCIDENT_CLOSED',
      'Cannot generate a QR code for a closed incident',
    )
  }

  // Deactivate any currently active tokens for this incident so there is
  // only ever one valid QR code at a time. Old tokens are kept for audit trail.
  await supabase
    .from('incident_qr_tokens')
    .update({ is_active: false })
    .eq('incident_id', incidentId)
    .eq('is_active', true)

  // Create the new token (token value is generated by the DB DEFAULT)
  const { data: newToken, error: insertError } = await supabase
    .from('incident_qr_tokens')
    .insert({
      incident_id: incidentId,
      organization_id: organizationId,
      created_by: memberId,
    })
    .select('id, token')
    .single()

  if (insertError || !newToken) {
    console.error('[createQrToken] insert failed:', insertError?.code)
    throw new CreateQrTokenError('DB_ERROR', 'Failed to create QR token')
  }

  return { id: newToken.id, token: newToken.token }
}
